/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package spa.relaxg12.Vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import spa.relaxg12.Modelo.Producto;
import spa.relaxg12.Modelo.Tratamiento;
import spa.relaxg12.Persistencia.ProductoData;
import spa.relaxg12.Persistencia.TratamientoData;
import java.sql.SQLException;

/**
 *
 * @author patri
 */
public class VistasTratamiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistasTratamiento
     */
    public VistasTratamiento() {
        initComponents();
        ProductoData productoData = new ProductoData();
        cargarComboProductos(productoData.cargarProductos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboEspecialidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        comboProducto = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnGuardarTrat = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDetalle = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnAltaBaja = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("Especialidad");

        comboEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facial", "Corporal", "Relajacion", "Estetico" }));
        comboEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEspecialidadActionPerformed(evt);
            }
        });

        jLabel3.setText("Productos");

        btnAgregar.setText("Añadir");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Detalle", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProducto);

        jLabel4.setText("Precio Total");

        btnGuardarTrat.setText("Guardar");
        btnGuardarTrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTratActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tratamiento");

        jLabel6.setText("Detalle");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAltaBaja.setText("Alta/Baja");
        btnAltaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaBajaActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spa/relaxg12/Vistas/img/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnGuardarTrat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAltaBaja)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDetalle, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboEspecialidad, javax.swing.GroupLayout.Alignment.LEADING, 0, 122, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarTrat)
                    .addComponent(btnSalir)
                    .addComponent(btnModificar)
                    .addComponent(btnAltaBaja))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validacionNombre() {
        String nombre = txtNombre.getText().trim();
        boolean valido = true;
        for (int i = 0; i < nombre.length(); i++) {
            char c = nombre.charAt(i);
            if (!Character.isLetter(c) && c != ' ') {
                valido = false;
                break;
            }
        }
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo nombre no debe estar vacio!");
            return false;
        } else if (valido == false) {
            JOptionPane.showMessageDialog(this, "Nombre: solo se permiten letras y espacios");
            txtNombre.setText("");
            return false;
        }
        return true;
    }

    public boolean validacionPrecio() {
        String numero = txtPrecio.getText().trim();
        boolean valido = true;

        for (int i = 0; i < numero.length(); i++) {
            char c = numero.charAt(i);
            if (!Character.isDigit(c) && c != '.') {
                valido = false;
                break;
            }
        }

        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo precio no debe estar vacio!");
            return false;
        } else if (!valido) {
            JOptionPane.showMessageDialog(this, "Precio: solo se permiten digitos y puntos (0-9)");
            txtPrecio.setText("");
            return false;
        }

        return true;
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblProducto.getModel();
        Producto producto = (Producto) comboProducto.getSelectedItem();
        String[] fila = {
            producto.getNombre(),
            producto.getDetalle(),
            producto.getStock().toString()
        };
        modelo.addRow(fila);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblProducto.getModel();
        int fila = tblProducto.getSelectedRow();
        if (fila != -1) {
            modelo.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarTratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTratActionPerformed

        ProductoData pdta = new ProductoData();
        if (validacionNombre() && validacionPrecio()) {
            ArrayList<Producto> lista = new ArrayList();
            DefaultTableModel modelo = (DefaultTableModel) tblProducto.getModel();
            for (int i = 0; i < modelo.getRowCount(); i++) {
                String nombre = modelo.getValueAt(i, 0).toString();
                lista.add(pdta.BuscarProducto(nombre));
            }

            String nombre = txtNombre.getText();
            String especialidad = comboEspecialidad.getSelectedItem().toString();
            String detalle = txtDetalle.getText();
            int duracion = 30;
            double costo = Double.parseDouble(txtPrecio.getText());
            Tratamiento tratamiento = new Tratamiento(nombre, especialidad, detalle, lista, duracion, costo, true);

            TratamientoData tratamientoData = new TratamientoData();
            Tratamiento tratNoEsta = tratamientoData.buscarTratramiento(nombre);
            boolean exito = false;
            if (tratNoEsta == null) {

                tratamientoData.guardarTratamiento(tratamiento);
                exito = false;
                for (Producto aux : lista) {

                    exito = tratamientoData.cargarTratamientoProducto(aux, tratamiento);

                }
            } else {
                JOptionPane.showMessageDialog(this, "No pueden duplicarse nombres de tratamiento.");
            }

            if (exito) {
                JOptionPane.showMessageDialog(this, "Productos guardados con Exito");
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar Productos");
            }
        }

    }//GEN-LAST:event_btnGuardarTratActionPerformed

    private void comboEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEspecialidadActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        TratamientoData tratamientoData = new TratamientoData();
        if (validacionNombre() && validacionPrecio()) {
            ProductoData pdta = new ProductoData();
            ArrayList<Producto> lista = new ArrayList();
            DefaultTableModel modelo = (DefaultTableModel) tblProducto.getModel();
            for (int i = 0; i < modelo.getRowCount(); i++) {
                String nombre = modelo.getValueAt(i, 0).toString();
                lista.add(pdta.BuscarProducto(nombre));
            }

            String nombre = txtNombre.getText();
            String especialidad = comboEspecialidad.getSelectedItem().toString();
            String detalle = txtDetalle.getText();
            int duracion = 30;
            double costo = Double.parseDouble(txtPrecio.getText());
            Tratamiento tratamiento = new Tratamiento(nombre, especialidad, detalle, lista, duracion, costo, true);
            tratamientoData.modificarTratamiento(tratamiento);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAltaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaBajaActionPerformed
        TratamientoData tratamientoData = new TratamientoData();
        Tratamiento tratamiento = tratamientoData.buscarTratramiento(txtNombre.getText());
        if (tratamiento.isActivo() == true) {
            tratamientoData.bajaTratamiento(tratamiento);
        } else if (tratamiento.isActivo() == false) {
            tratamientoData.altaTratamiento(tratamiento);
        }
    }//GEN-LAST:event_btnAltaBajaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
        TratamientoData tratData = new TratamientoData();
        if (validacionNombre()) {
            Tratamiento tratamiento = tratData.buscarTratramiento(txtNombre.getText());
            int index;
            if (tratamiento.getEspecialidad().equalsIgnoreCase("facial")) {
                index = 0;
            } else if (tratamiento.getEspecialidad().equalsIgnoreCase("Corporal")) {
                index = 1;
            } else if (tratamiento.getEspecialidad().equalsIgnoreCase("Relajacion")) {
                index = 2;
            } else {
                index = 3;
            }
            comboEspecialidad.setSelectedIndex(index);
            txtDetalle.setText(tratamiento.getDetalle());
            txtPrecio.setText(tratamiento.getCosto().toString());
        }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAltaBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarTrat;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboEspecialidad;
    private javax.swing.JComboBox<Producto> comboProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtDetalle;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
 public void cargarComboProductos(ArrayList<Producto> listado) {

        for (Producto aux : listado) {
            comboProducto.addItem(aux);

        }
    }

}
