/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package spa.relaxg12.Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import spa.relaxg12.Modelo.Cliente;
import spa.relaxg12.Modelo.Sesion;
import spa.relaxg12.Persistencia.ClienteData;
import spa.relaxg12.Persistencia.DiaDeSpaData;
import spa.relaxg12.Persistencia.SesionData;

/**
 *
 * @author Leandro
 */
public class VistasTurnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistasTurnos
     */
    public VistasTurnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEstado = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSesiones = new javax.swing.JTable();
        dateFecha = new com.toedter.calendar.JDateChooser();
        txtDni = new javax.swing.JTextField();
        labelDni = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarDni = new javax.swing.JButton();
        btnBuscarFecha = new javax.swing.JButton();
        btnEliminarSesion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnSesionFinalizada = new javax.swing.JButton();
        rbtnEnCurso = new javax.swing.JRadioButton();
        rbtnFinalizadas = new javax.swing.JRadioButton();

        tblSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Fecha", "Hora", "Sesion", "ID Sesion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSesiones);

        labelDni.setText("DNI");

        jLabel2.setText("Fecha");

        btnBuscarDni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spa/relaxg12/Vistas/img/lupa.png"))); // NOI18N
        btnBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDniActionPerformed(evt);
            }
        });

        btnBuscarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spa/relaxg12/Vistas/img/lupa.png"))); // NOI18N
        btnBuscarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFechaActionPerformed(evt);
            }
        });

        btnEliminarSesion.setText("Eliminar Sesion");
        btnEliminarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSesionActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnSesionFinalizada.setText("Atencion Finalizada");
        btnSesionFinalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionFinalizadaActionPerformed(evt);
            }
        });

        groupEstado.add(rbtnEnCurso);
        rbtnEnCurso.setSelected(true);
        rbtnEnCurso.setText("En curso");

        groupEstado.add(rbtnFinalizadas);
        rbtnFinalizadas.setText("Finalizadas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(labelDni)
                        .addGap(18, 18, 18)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminarSesion)
                                .addGap(18, 18, 18)
                                .addComponent(btnSesionFinalizada)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnEnCurso)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnFinalizadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarFecha)
                    .addComponent(btnBuscarDni)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDni))
                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEliminarSesion)
                    .addComponent(btnSesionFinalizada)
                    .addComponent(rbtnEnCurso)
                    .addComponent(rbtnFinalizadas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validacionDni() {
        String numero = txtDni.getText().trim();
        boolean valido = true;

        for (int i = 0; i < numero.length(); i++) {
            char c = numero.charAt(i);
            if (!Character.isDigit(c)) {
                valido = false;
                break;
            }
        }

        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo DNI no debe estar vacio!");
            return false;
        } else if (!valido) {
            JOptionPane.showMessageDialog(this, "DNI: solo se permiten digitos (0-9)");
            txtDni.setText("");
            return false;
        } else if (numero.length() < 7) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener al menos 7 caracteres");
            return false;
        }

        return true;
    }

    private void btnBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDniActionPerformed
        if (validacionDni()) {
            int dni = Integer.parseInt(txtDni.getText());
            ClienteData clienteData = new ClienteData();
            DefaultTableModel modelo = (DefaultTableModel) tblSesiones.getModel();
            modelo.setRowCount(0);
            DiaDeSpaData diaDeSpaData = new DiaDeSpaData();
            ArrayList<Sesion> listado = null;
            Cliente cliente = null;
            if (rbtnEnCurso.isSelected()) {
                listado = diaDeSpaData.buscarSesionesActivasPorDni(dni);
                cliente = clienteData.buscarClienteDni(dni);
            } else if (rbtnFinalizadas.isSelected()) {
                listado = diaDeSpaData.buscarSesionesInactivasPorDni(dni);
                cliente = clienteData.buscarClienteDni(dni);
            }

            try {
                for (Sesion aux : listado) {

                    String[] fila = {
                        String.valueOf(cliente.getDni()),
                        cliente.getNombre() + " " + cliente.getApellido(),
                        aux.getFechaInicio().toString(),
                        aux.getHora().toString(),
                        aux.getTratamientos().toString(),
                        String.valueOf(aux.getIdSesion())
                    };
                    modelo.addRow(fila);
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, "No se encontraron sesiones para ese DNI: " + dni);
            }
        }
    }//GEN-LAST:event_btnBuscarDniActionPerformed

    private void btnEliminarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSesionActionPerformed
        Sesion sesion = null;
        SesionData sesionData = new SesionData();
        DefaultTableModel modelo = (DefaultTableModel) tblSesiones.getModel();
        int fila = tblSesiones.getSelectedRow();
        if (fila != -1) {
            int id = Integer.parseInt(modelo.getValueAt(fila, 5).toString());
            sesionData.eliminarSesionDiaDeSpa(id);
            sesionData.eliminarSesion(id);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una sesion de la tabla");
        }
    }//GEN-LAST:event_btnEliminarSesionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFechaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblSesiones.getModel();
        modelo.setRowCount(0);
        DiaDeSpaData diaDeSpaData = new DiaDeSpaData();
        ArrayList<Sesion> listado = null;
        try {
            LocalDate fecha = dateFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            if (rbtnEnCurso.isSelected()) {
                listado = diaDeSpaData.buscarSesionesActivasPorFecha(fecha);
            } else if (rbtnFinalizadas.isSelected()) {
                listado = diaDeSpaData.buscarSesionesInactivasPorFecha(fecha);
            }
            for (Sesion sesion : listado) {
                Cliente cliente = diaDeSpaData.buscarClientePorSesion(sesion.getIdSesion());

                String[] fila = {
                    String.valueOf(cliente.getDni()),
                    cliente.getNombre() + " " + cliente.getApellido(),
                    sesion.getFechaInicio().toString(),
                    sesion.getHora().toString(),
                    sesion.getTratamientos().toString(),
                    String.valueOf(sesion.getIdSesion())
                };
                modelo.addRow(fila);
            }

            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron sesiones para la fecha: " + fecha);
            }

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha valida!");
        }
    }//GEN-LAST:event_btnBuscarFechaActionPerformed

    private void btnSesionFinalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionFinalizadaActionPerformed
        DiaDeSpaData diaDeSpaData = new DiaDeSpaData();
        DefaultTableModel modelo = (DefaultTableModel) tblSesiones.getModel();
        int fila = tblSesiones.getSelectedRow();
        if (fila != -1) {
            int id = Integer.parseInt(modelo.getValueAt(fila, 5).toString());
            diaDeSpaData.sesionFinalizada(id);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una sesion de la tabla");
        }
    }//GEN-LAST:event_btnSesionFinalizadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDni;
    private javax.swing.JButton btnBuscarFecha;
    private javax.swing.JButton btnEliminarSesion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSesionFinalizada;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.ButtonGroup groupEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDni;
    private javax.swing.JRadioButton rbtnEnCurso;
    private javax.swing.JRadioButton rbtnFinalizadas;
    private javax.swing.JTable tblSesiones;
    private javax.swing.JTextField txtDni;
    // End of variables declaration//GEN-END:variables
}
