/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package spa.relaxg12.Vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import spa.relaxg12.Modelo.Profesional;
import spa.relaxg12.Persistencia.ProfesionalData;

/**
 *
 * @author Leandro
 */
public class VistasProfesional extends javax.swing.JInternalFrame {

    private ProfesionalData profData;
    private DefaultTableModel modelo;
    private ArrayList<Profesional> listaProf;

    /**
     * Creates new form VistasProfesional
     */
    public VistasProfesional() {
        initComponents();

        profData = new ProfesionalData();
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // ninguna celda editable
            }
        };
        listaProf = new ArrayList<>();

        armarCabecera();
        armarCombo();
        armarComboBuscar();
        listarProfesionales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEstado = new javax.swing.ButtonGroup();
        rbtnInactivo = new javax.swing.JRadioButton();
        rbtnActivo = new javax.swing.JRadioButton();
        btnAltaBaja = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProfesionales = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cmbEspecialidadBuscar = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtMatricula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cmbEspecialidad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        groupEstado.add(rbtnInactivo);
        rbtnInactivo.setText("Inactivos");
        rbtnInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInactivoActionPerformed(evt);
            }
        });

        groupEstado.add(rbtnActivo);
        rbtnActivo.setSelected(true);
        rbtnActivo.setText("Activos");
        rbtnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnActivoActionPerformed(evt);
            }
        });

        btnAltaBaja.setText("Alta / Baja");
        btnAltaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaBajaActionPerformed(evt);
            }
        });

        tblProfesionales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProfesionales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProfesionalesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProfesionales);

        jLabel7.setText("Especialidad");

        cmbEspecialidadBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEspecialidadBuscar.setSelectedIndex(-1);
        cmbEspecialidadBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEspecialidadBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spa/relaxg12/Vistas/img/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setText("Matricula");

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spa/relaxg12/Vistas/img/actualizar.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre");

        jLabel11.setText("Apellido");

        jLabel12.setText("Telefono");

        jLabel13.setText("Matricula");

        jLabel14.setText("Especialidad");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        cmbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Gestor de Profesionales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbEspecialidad, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAltaBaja)
                            .addGap(38, 38, 38)
                            .addComponent(rbtnActivo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbtnInactivo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir1))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbEspecialidadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cmbEspecialidadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscar)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cmbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaBaja)
                    .addComponent(rbtnActivo)
                    .addComponent(rbtnInactivo)
                    .addComponent(btnSalir1)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Validaciones
    public boolean validacionApellido() {
        String apellido = txtApellido.getText().trim();
        boolean valido = true;
        for (int i = 0; i < apellido.length(); i++) {
            char c = apellido.charAt(i);
            if (!Character.isLetter(c) && c != ' ') {
                valido = false;
                break;
            }
        }
        if (apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo apellido no debe estar vacio!");
            return false;
        } else if (valido == false) {
            JOptionPane.showMessageDialog(this, "Apellido: solo se permiten letras y espacios");
            txtApellido.setText("");
            return false;
        }
        return true;
    }

    public boolean validacionNombre() {
        String nombre = txtNombre.getText().trim();
        boolean valido = true;
        for (int i = 0; i < nombre.length(); i++) {
            char c = nombre.charAt(i);
            if (!Character.isLetter(c) && c != ' ') {
                valido = false;
                break;
            }
        }
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo nombre no debe estar vacio!");
            return false;
        } else if (valido == false) {
            JOptionPane.showMessageDialog(this, "Nombre: solo se permiten letras y espacios");
            txtNombre.setText("");
            return false;
        }
        return true;
    }

    public boolean validacionTel() {
        String numero = txtTelefono.getText().trim();
        boolean valido = true;

        for (int i = 0; i < numero.length(); i++) {
            char c = numero.charAt(i);
            if (!Character.isDigit(c)) {
                valido = false;
                break;
            }
        }

        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo telefono no debe estar vacio!");
            return false;
        } else if (!valido) {
            JOptionPane.showMessageDialog(this, "Telefono: solo se permiten digitos (0-9)");
            txtTelefono.setText("");
            return false;
        } else if (numero.length() < 10) {
            JOptionPane.showMessageDialog(this, "El telefono debe tener al menos 10 caracteres");
            return false;
        }

        return true;
    }

    public void limpiarCampos() {
        txtMatricula.setText("");
        txtApellido.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        cmbEspecialidad.setSelectedIndex(-1);
    }

    public void armarCombo() { //Este combo se debe llenar con las especialidades requeridas que vaya a tener el spa
        cmbEspecialidad.removeAllItems();

        cmbEspecialidad.addItem("Esteticista");
        cmbEspecialidad.addItem("Masajista");
        cmbEspecialidad.addItem("Cosmetólogo/a");
        cmbEspecialidad.addItem("Manicurista");
        cmbEspecialidad.addItem("Pedicurista");
    }

    public void armarComboBuscar() {
        cmbEspecialidadBuscar.removeAllItems();

        ArrayList<String> listaEspecialidad = profData.listarEspecialidades();
        for (String it : listaEspecialidad) {
            cmbEspecialidadBuscar.addItem(it);
        }

    }

    public void armarCabecera() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Matricula");
        filaCabecera.add("Nombre");
        filaCabecera.add("Apellido");
        filaCabecera.add("Telefono");
        filaCabecera.add("Especialidad");
        filaCabecera.add("Estado");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        tblProfesionales.setModel(modelo);
    }

    public void listarPorEspecialidad(String especialidad) {
        modelo.setRowCount(0);
        ArrayList<Profesional> listado = profData.listarProfesionalesPorEspecialidad(especialidad);

        for (Profesional p : listado) {
            Object[] row = {p.getMatricula(), p.getNombre(), p.getApellido(), p.getTelefono(), p.getEspecialidad(), p.isEstado()};
            modelo.addRow(row);
        }
    }

    public void listarProfesionales() {
        modelo.setRowCount(0);
        ArrayList<Profesional> listado = profData.listarProfesionales();

        for (Profesional p : listado) {
            Object[] row = {p.getMatricula(), p.getNombre(), p.getApellido(), p.getTelefono(), p.getEspecialidad(), p.isEstado()};
            modelo.addRow(row);
        }

    }

    public void borrarFila() {
        int indice = modelo.getRowCount() - 1;

        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    public void cargarInactivos() {
        borrarFila();
        listaProf = profData.listarProfesionalesInactivos();
        for (Profesional p : listaProf) {
            Object[] row = {p.getMatricula(), p.getNombre(), p.getApellido(), p.getTelefono(), p.getEspecialidad(), p.isEstado()};
            modelo.addRow(row);
        }
    }

    public void cargarActivos() {
        borrarFila();
        ArrayList<Profesional> lista = profData.listarProfesionalesActivos();
        for (Profesional p : lista) {
            Object[] row = {p.getMatricula(), p.getNombre(), p.getApellido(), p.getTelefono(), p.getEspecialidad(), p.isEstado()};
            modelo.addRow(row);
        }
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!txtBuscar.getText().isEmpty()) {
            boolean exito = true;
            String matricula = txtBuscar.getText().trim();
            for (int i = 0; i < tblProfesionales.getRowCount(); i++) {
                String valorMatricula = tblProfesionales.getValueAt(i, 0).toString();
                if (valorMatricula.equalsIgnoreCase(matricula)) {
                    tblProfesionales.setRowSelectionInterval(i, i);
                    tblProfesionales.scrollRectToVisible(tblProfesionales.getCellRect(i, 0, true));
                    exito = true;
                    return;
                } else {
                    exito = false;
                }
            }
            if (exito == false) {
                JOptionPane.showMessageDialog(this, "No se eoncontro profesional con matricula: " + matricula);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo matricula no debe estar vacio!");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (rbtnActivo.isSelected()) {
            cargarActivos();
        } else {
            cargarInactivos();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnAltaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaBajaActionPerformed
        Profesional prof = null;
        int fila = tblProfesionales.getSelectedRow();
        if (fila != -1) {
            String matricula = (String) modelo.getValueAt(fila, 0);
            prof = profData.buscarProfesionalPorMatricula(matricula);
            boolean estado = prof.isEstado();
            if (estado == true) {
                profData.darBajaProfesional(matricula);
            } else {
                profData.darAltaProfesional(matricula);
            }

            if (rbtnActivo.isSelected()) {
                cargarActivos();
            } else {
                cargarInactivos();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un profesional de la tabla");
        }
    }//GEN-LAST:event_btnAltaBajaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      Profesional prof=  profData.buscarProfesionalPorMatricula(txtMatricula.getText());
      if( prof== null){
        try {
           
            if (validacionNombre() && validacionApellido() && validacionTel() && !txtMatricula.getText().isEmpty()) {
                String matricula = txtMatricula.getText();
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                String telefono = txtTelefono.getText();
                String especialidad = (String) cmbEspecialidad.getSelectedItem();
                prof = new Profesional(matricula, nombre, apellido, telefono, especialidad, true);
            } else {
                JOptionPane.showMessageDialog(this, "Debe cargar los campos correspondientes");
            }
            profData.crearProfesional(prof);
            if (rbtnActivo.isSelected()) {
                cargarActivos();
            } else {
                cargarInactivos();
            }
        } catch (NullPointerException e) {
        }
      }else{
          JOptionPane.showMessageDialog(this, "Ya existe un profesional con esa matricula");
      }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            Profesional prof = null;
            if (validacionNombre() && validacionApellido() && validacionTel() && !txtMatricula.getText().isEmpty()) {
                String matricula = txtMatricula.getText();
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                String telefono = txtTelefono.getText();
                String especialidad = (String) cmbEspecialidad.getSelectedItem();
                prof = new Profesional(matricula, nombre, apellido, telefono, especialidad, true);
            }
            profData.modificarProfesional(prof);
            if (rbtnActivo.isSelected()) {
                cargarActivos();
            } else {
                cargarInactivos();
            }
        } catch (NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Debe Cargar un Profesional o seleccionarlo de la tabla");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblProfesionalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProfesionalesMouseClicked

        Profesional p = null;
        int fila = tblProfesionales.getSelectedRow();
        if (fila != -1) {
            String matricula = (String) modelo.getValueAt(fila, 0);
            p = profData.buscarProfesionalPorMatricula(matricula);
        }
        txtMatricula.setText(p.getMatricula());
        txtNombre.setText(p.getNombre());
        txtApellido.setText(p.getApellido());
        txtTelefono.setText(p.getTelefono());
        cmbEspecialidad.setSelectedItem(p.getEspecialidad());

    }//GEN-LAST:event_tblProfesionalesMouseClicked

    private void rbtnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnActivoActionPerformed
        cargarActivos();
    }//GEN-LAST:event_rbtnActivoActionPerformed

    private void rbtnInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInactivoActionPerformed
        cargarInactivos();
    }//GEN-LAST:event_rbtnInactivoActionPerformed

    private void cmbEspecialidadBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEspecialidadBuscarActionPerformed
        String especialidad = (String) cmbEspecialidadBuscar.getSelectedItem();

        listarPorEspecialidad(especialidad);
    }//GEN-LAST:event_cmbEspecialidadBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAltaBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<String> cmbEspecialidad;
    private javax.swing.JComboBox<String> cmbEspecialidadBuscar;
    private javax.swing.ButtonGroup groupEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtnActivo;
    private javax.swing.JRadioButton rbtnInactivo;
    private javax.swing.JTable tblProfesionales;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
