/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package spa.relaxg12.Vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import spa.relaxg12.Modelo.Cliente;
import spa.relaxg12.Persistencia.ClienteData;

/**
 *
 * @author patri
 */
public class VistasCliente extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private ClienteData clienteData;

    /**
     * Creates new form VistasCliente
     */
    public VistasCliente() {
        initComponents();

        clienteData = new ClienteData();
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // ninguna celda editable
            }
        };

        armarCabecera();
        cargarClientesActivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEstado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAfecciones = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAltaBaja = new javax.swing.JButton();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnLimpiarCampos = new javax.swing.JButton();
        rbtnActivo = new javax.swing.JRadioButton();
        rbtnInactivo = new javax.swing.JRadioButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("DNI");

        jLabel4.setText("Telefono");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Gestor de Clientes");

        jLabel6.setText("Afecciones");

        txtAfecciones.setColumns(20);
        txtAfecciones.setRows(5);
        jScrollPane1.setViewportView(txtAfecciones);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spa/relaxg12/Vistas/img/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel7.setText("DNI");

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spa/relaxg12/Vistas/img/actualizar.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAltaBaja.setText("Alta / Baja");
        btnAltaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaBajaActionPerformed(evt);
            }
        });

        jLabel8.setText("Edad");

        btnLimpiarCampos.setText("Limpiar");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        groupEstado.add(rbtnActivo);
        rbtnActivo.setSelected(true);
        rbtnActivo.setText("Activos");
        rbtnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnActivoActionPerformed(evt);
            }
        });

        groupEstado.add(rbtnInactivo);
        rbtnInactivo.setText("Inactivos");
        rbtnInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInactivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23))
                            .addComponent(btnAgregar)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiarCampos))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAltaBaja)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnActivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnInactivo)
                        .addGap(118, 118, 118)
                        .addComponent(btnSalir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizar))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbtnActivo)
                                .addComponent(rbtnInactivo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAgregar)
                                .addComponent(btnModificar)
                                .addComponent(btnAltaBaja)
                                .addComponent(btnLimpiarCampos)))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Validaciones
    public boolean validacionApellido() {
        String apellido = txtApellido.getText().trim();
        boolean valido = true;
        for (int i = 0; i < apellido.length(); i++) {
            char c = apellido.charAt(i);
            if (!Character.isLetter(c) && c != ' ') {
                valido = false;
                break;
            }
        }
        if (apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo apellido no debe estar vacio!");
            return false;
        } else if (valido == false) {
            JOptionPane.showMessageDialog(this, "Apellido: solo se permiten letras y espacios");
            txtApellido.setText("");
            return false;
        }
        return true;
    }

    public boolean validacionNombre() {
        String nombre = txtNombre.getText().trim();
        boolean valido = true;
        for (int i = 0; i < nombre.length(); i++) {
            char c = nombre.charAt(i);
            if (!Character.isLetter(c) && c != ' ') {
                valido = false;
                break;
            }
        }
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo nombre no debe estar vacio!");
            return false;
        } else if (valido == false) {
            JOptionPane.showMessageDialog(this, "Nombre: solo se permiten letras y espacios");
            txtNombre.setText("");
            return false;
        }
        return true;
    }

    public boolean validacionDni() {
        String numero = txtDni.getText().trim();
        boolean valido = true;

        for (int i = 0; i < numero.length(); i++) {
            char c = numero.charAt(i);
            if (!Character.isDigit(c)) {
                valido = false;
                break;
            }
        }

        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo DNI no debe estar vacio!");
            return false;
        } else if (!valido) {
            JOptionPane.showMessageDialog(this, "DNI: solo se permiten digitos (0-9)");
            txtDni.setText("");
            return false;
        } else if (numero.length() < 7) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener al menos 7 caracteres");
            return false;
        }

        return true;
    }

    public boolean validacionDniBuscar() {
        String numero = txtBuscar.getText().trim();
        boolean valido = true;

        for (int i = 0; i < numero.length(); i++) {
            char c = numero.charAt(i);
            if (!Character.isDigit(c)) {
                valido = false;
                break;
            }
        }

        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo DNI no debe estar vacio!");
            return false;
        } else if (!valido) {
            JOptionPane.showMessageDialog(this, "DNI: solo se permiten digitos (0-9)");
            txtBuscar.setText("");
            return false;
        } else if (numero.length() < 7) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener al menos 7 caracteres");
            return false;
        }

        return true;
    }
    
    public boolean validacionTel() {
        String numero = txtTelefono.getText().trim();
        boolean valido = true;

        for (int i = 0; i < numero.length(); i++) {
            char c = numero.charAt(i);
            if (!Character.isDigit(c)) {
                valido = false;
                break;
            }
        }

        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo telefono no debe estar vacio!");
            return false;
        } else if (!valido) {
            JOptionPane.showMessageDialog(this, "Telefono: solo se permiten digitos (0-9)");
            txtTelefono.setText("");
            return false;
        } else if (numero.length() < 10) {
            JOptionPane.showMessageDialog(this, "El telefono debe tener al menos 10 caracteres");
            return false;
        }

        return true;
    }

    public boolean validacionEdad() {
        String numero = txtEdad.getText().trim();
        boolean valido = true;
        int numInt = 0;

        for (int i = 0; i < numero.length(); i++) {
            char c = numero.charAt(i);
            if (!Character.isDigit(c)) {
                valido = false;
                break;
            }
        }

        if (!numero.isBlank() && valido) {
            numInt = Integer.parseInt(numero);
        }

        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo edad no debe estar vacio!");
            return false;
        } else if (numInt < 1 || numInt > 110) {
            JOptionPane.showMessageDialog(this, "Edad inválida: debe estar entre 1 y 110 años");
            txtEdad.setText("");
            return false;
        }

        return true;
    }

    public boolean validacionAfec() {
        String afec = txtAfecciones.getText();
        boolean valido = true;
        for (int i = 0; i < afec.length(); i++) {
            char c = afec.charAt(i);
            if (!Character.isLetter(c) && c!= ' ' && c != '.' && c != ',' && c != ':') {
                valido = false;
                break;
            }
        }
        if (valido == false) {
            JOptionPane.showMessageDialog(this, "Afecciones: solo se permiten letras y espacios");
            txtAfecciones.setText("");
            return false;
        }
        return true;
    }

    public void limpiarCampos() {
        txtDni.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        txtTelefono.setText("");
        txtAfecciones.setText("");
    }

    public void armarCabecera() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("DNI");
        filaCabecera.add("Nombre");
        filaCabecera.add("Apellido");
        filaCabecera.add("Edad");
        filaCabecera.add("Telefono");
        filaCabecera.add("Estado");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        tblClientes.setModel(modelo);
    }

    public void listarClientes() {
        modelo.setRowCount(0);
        ArrayList<Cliente> listado = clienteData.listarClientes();

        for (Cliente c : listado) {
            Object[] row = {c.getDni(), c.getNombre(), c.getApellido(), c.getEdad(), c.getTelefono(), c.isEstado()};
            modelo.addRow(row);
        }
    }

    public void cargarClientesInactivos() {
        modelo.setRowCount(0);
        ArrayList<Cliente> listado = clienteData.listarClientesInactivos();

        for (Cliente c : listado) {
            Object[] row = {c.getDni(), c.getNombre(), c.getApellido(), c.getEdad(), c.getTelefono(), c.isEstado()};
            modelo.addRow(row);
        }
    }

    public void cargarClientesActivos() {
        modelo.setRowCount(0);
        ArrayList<Cliente> listado = clienteData.listarClientesActivos();

        for (Cliente c : listado) {
            Object[] row = {c.getDni(), c.getNombre(), c.getApellido(), c.getEdad(), c.getTelefono(), c.isEstado()};
            modelo.addRow(row);
        }
    }

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            Cliente cliente = null;
            if (validacionNombre() && validacionApellido() && validacionDni() && validacionEdad() && validacionTel() && validacionAfec()) {
                int dni = Integer.parseInt(txtDni.getText());
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                int edad = Integer.parseInt(txtEdad.getText());
                long telefono = Long.parseLong(txtTelefono.getText());
                String afecciones = txtAfecciones.getText();
                cliente = new Cliente(dni, nombre, apellido, edad, telefono, afecciones, true);
            }
            clienteData.crearCliente(cliente);
            if (rbtnActivo.isSelected()) {
                cargarClientesActivos();
            } else {
                cargarClientesInactivos();
            }
        } catch (NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Debe llenar los campos");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (rbtnActivo.isSelected()) {
            cargarClientesActivos();
        } else {
            cargarClientesInactivos();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (validacionDniBuscar()) {
            int dniNum = Integer.parseInt(txtBuscar.getText());
            for (int i = 0; i < tblClientes.getRowCount(); i++) {
                String dni = txtBuscar.getText();
                String valorDni = tblClientes.getValueAt(i, 0).toString();
                if (valorDni.equalsIgnoreCase(dni)) {
                    tblClientes.setRowSelectionInterval(i, i);
                    tblClientes.scrollRectToVisible(tblClientes.getCellRect(i, 0, true));
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            Cliente cliente = null;
            if (validacionNombre() && validacionApellido() && validacionDni() && validacionEdad() && validacionTel() && validacionAfec()) {
                int dni = Integer.parseInt(txtDni.getText());
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                int edad = Integer.parseInt(txtEdad.getText());
                long telefono = Long.parseLong(txtTelefono.getText());
                String afecciones = txtAfecciones.getText();
                cliente = new Cliente(dni, nombre, apellido, edad, telefono, afecciones, true);
            }
            clienteData.modificarCliente(cliente);
            if (rbtnActivo.isSelected()) {
                cargarClientesActivos();
            } else {
                cargarClientesInactivos();
            }
        } catch (NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Debe Cargar un Cliente o seleccionarlo de la tabla");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAltaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaBajaActionPerformed
        Cliente cliente = null;
        int fila = tblClientes.getSelectedRow();
        if (fila != -1) {
            int dni = (Integer) modelo.getValueAt(fila, 0);
            cliente = clienteData.buscarClienteDni(dni);
            boolean estado = cliente.isEstado();
            if (estado == true) {
                clienteData.darBajaCliente(dni);
                cargarClientesInactivos();
            } else {
                clienteData.darAltaCliente(dni);
                if (rbtnActivo.isSelected()) {
                    cargarClientesActivos();
                } else {
                    cargarClientesInactivos();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la tabla");
        }
    }//GEN-LAST:event_btnAltaBajaActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        Cliente cliente = null;
        int fila = tblClientes.getSelectedRow();
        if (fila != -1) {
            int dni = (Integer) modelo.getValueAt(fila, 0);
            cliente = clienteData.buscarClienteDni(dni);
        }
        txtDni.setText(String.valueOf(cliente.getDni()));
        txtNombre.setText(cliente.getNombre());
        txtApellido.setText(cliente.getApellido());
        txtEdad.setText(String.valueOf(cliente.getEdad()));
        txtTelefono.setText(String.valueOf(cliente.getTelefono()));
        txtAfecciones.setText(cliente.getAfecciones());
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void rbtnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnActivoActionPerformed
        cargarClientesActivos();
    }//GEN-LAST:event_rbtnActivoActionPerformed

    private void rbtnInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInactivoActionPerformed
        cargarClientesInactivos();
    }//GEN-LAST:event_rbtnInactivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAltaBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup groupEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtnActivo;
    private javax.swing.JRadioButton rbtnInactivo;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextArea txtAfecciones;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
