/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package spa.relaxg12.Vistas;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.IntStream;
import spa.relaxg12.Modelo.Consultorio;
import spa.relaxg12.Modelo.Instalacion;
import spa.relaxg12.Modelo.Profesional;
import spa.relaxg12.Modelo.Tratamiento;
import spa.relaxg12.Persistencia.InstalacionData;
import spa.relaxg12.Persistencia.ProfesionalData;
import spa.relaxg12.Persistencia.SesionData;
import spa.relaxg12.Persistencia.TratamientoData;

/**
 *
 * @author Leandro
 */
public class VistasSesion extends javax.swing.JInternalFrame {

    private SesionData sesionData;
    private ProfesionalData profData;
    private TratamientoData tratData;

    /**
     * Creates new form VistasSesion
     */
    public VistasSesion() {
        initComponents();

        this.sesionData = new SesionData();
        this.profData = new ProfesionalData();
        this.tratData = new TratamientoData();

        cargarComboInstalacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbEspecialidad = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTratamiento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbProfesional = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        cmbHora = new javax.swing.JComboBox<>();
        cmbInstalaciones = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbConsultorio = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtMontoSesion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel13.setText("Tipo de Tratamiento");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facial", "Corporal", "Relajacion", "Estetico" }));
        cmbTipo.setSelectedIndex(-1);
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        cmbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEspecialidadActionPerformed(evt);
            }
        });

        jLabel14.setText("Especialidad");

        jLabel6.setText("Tratamiento");

        cmbTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTratamientoActionPerformed(evt);
            }
        });

        jLabel7.setText("Profesional");

        jLabel9.setText("Fecha /hora");

        jLabel10.setText("Hora");

        cmbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00", "9:30", "10:00", "10:30", "11:00 ", "11:30 ", "12:00 " }));
        cmbHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHoraActionPerformed(evt);
            }
        });

        cmbInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInstalacionesActionPerformed(evt);
            }
        });

        jLabel11.setText("Instalaciones");

        jLabel8.setText("Consultorio");

        jLabel16.setText("Monto");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Gestor de Sesiones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel16))
                    .addGap(39, 39, 39)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbTratamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbProfesional, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbInstalaciones, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbConsultorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(txtMontoSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                    .addGap(52, 52, 52)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnSalir))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(cmbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cmbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cmbProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cmbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel9)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbInstalaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(cmbConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtMontoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(75, 75, 75)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public double calculoMontoTotal() {
        Tratamiento trat;
        Instalacion inst;
        double montoTrat;
        double montoInst;
        double montoTotal = 0;

        if (cmbTratamiento.getSelectedIndex() != -1 && cmbInstalaciones.getSelectedIndex() != -1) {

            trat = (Tratamiento) cmbTratamiento.getSelectedItem();
            inst = (Instalacion) cmbInstalaciones.getSelectedItem();
            montoTrat = trat.getCosto();
            montoInst = inst.getPrecioPor30min();

            montoTotal = montoTrat + montoInst;
        } else if (cmbTratamiento.getSelectedIndex() != -1) {
            trat = (Tratamiento) cmbTratamiento.getSelectedItem();
            montoTrat = trat.getCosto();
            montoTotal = montoTrat;

        } else if (cmbInstalaciones.getSelectedIndex() != -1) {
            inst = (Instalacion) cmbInstalaciones.getSelectedItem();
            montoInst = inst.getPrecioPor30min();
            montoTotal = montoInst;
        }
        return montoTotal;
    }

    public void cargarComboTrat() {
        cmbTratamiento.removeAllItems();
        TratamientoData tratData = new TratamientoData();
        if (cmbTipo.getSelectedIndex() != -1) {
            ArrayList<Tratamiento> listado = tratData.listarTratamientos(cmbTipo.getSelectedItem().toString());
            for (Tratamiento aux : listado) {
                cmbTratamiento.addItem(aux);
            }
        }
        cmbTratamiento.setSelectedIndex(-1);
    }

    public void cargarComboProfesional() {
        cmbProfesional.removeAllItems();
        ProfesionalData profData = new ProfesionalData();
        if (cmbEspecialidad.getSelectedIndex() != -1) {
            ArrayList<Profesional> listado = profData.listarProfesionalesPorEspecialidad(cmbEspecialidad.getSelectedItem().toString());
            for (Profesional aux : listado) {
                cmbProfesional.addItem(aux);
            }
        }
        cmbProfesional.setSelectedIndex(-1);
    }

    public void cargarComboEspecialidad() {
        int tipo = cmbTipo.getSelectedIndex();
        if (tipo != -1) {
            if (cmbTipo.getSelectedItem().toString().equalsIgnoreCase("Facial")) {
                cmbEspecialidad.removeAllItems();
                String esp1 = "Esteticista";
                String esp2 = "Cosmetologo/a";
                cmbEspecialidad.addItem(esp1);
                cmbEspecialidad.addItem(esp2);
            } else if (cmbTipo.getSelectedItem().toString().equalsIgnoreCase("Corporal")) {
                cmbEspecialidad.removeAllItems();
                String esp1 = "Masajista";
                String esp2 = "Pedicurista";
                cmbEspecialidad.addItem(esp1);
                cmbEspecialidad.addItem(esp2);
            } else if (cmbTipo.getSelectedItem().toString().equalsIgnoreCase("Estetico")) {
                cmbEspecialidad.removeAllItems();
                String esp1 = "Esteticista";
                String esp2 = "Manicurista";
                String esp3 = "Cosmetologo/a";
                cmbEspecialidad.addItem(esp1);
                cmbEspecialidad.addItem(esp2);
                cmbEspecialidad.addItem(esp3);
            }
        }
        cmbEspecialidad.setSelectedIndex(-1);
    }

    public void cargarComboInstalacion() {
        InstalacionData instData = new InstalacionData();
        ArrayList<Instalacion> listado = (ArrayList) instData.listarInstalacionesActivas();
        for (Instalacion aux : listado) {
            cmbInstalaciones.addItem(aux);
        }
        cmbInstalaciones.setSelectedIndex(-1);
    }

    public void cargarComboConsultorios() {
        SesionData sesionData = new SesionData();
        LocalDate fecha = dateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String hora = cmbHora.getSelectedItem().toString();
        String apto = cmbTipo.getSelectedItem().toString();
        ArrayList<Consultorio> listado = sesionData.buscarConsultoriosDisponibles(fecha, hora, apto);
        for (Consultorio aux : listado) {
            cmbConsultorio.addItem(aux);
        }
        cmbConsultorio.setSelectedIndex(-1);
    }

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        cargarComboEspecialidad();
        cargarComboTrat();
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void cmbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEspecialidadActionPerformed
        cargarComboProfesional();
    }//GEN-LAST:event_cmbEspecialidadActionPerformed

    private void cmbHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHoraActionPerformed
        try {
            cmbProfesional.removeAllItems();
            SesionData sesionData = new SesionData();
            ArrayList<Profesional> listado = null;
            LocalDate fecha = dateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String hora = cmbHora.getSelectedItem().toString();
            String especialidad = cmbEspecialidad.getSelectedItem().toString();
            listado = sesionData.buscarProfesionalesLibres(fecha, hora, especialidad);

            for (Profesional aux : listado) {
                cmbProfesional.addItem(aux.getNombre() + aux.getApellido());

            }
            cargarComboConsultorios();
        } catch (SQLException ex) {
            Logger.getLogger(VistasSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbHoraActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTratamientoActionPerformed
        txtMontoSesion.setText(String.valueOf(calculoMontoTotal()));
    }//GEN-LAST:event_cmbTratamientoActionPerformed

    private void cmbInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInstalacionesActionPerformed
        txtMontoSesion.setText(String.valueOf(calculoMontoTotal()));
    }//GEN-LAST:event_cmbInstalacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Object> cmbConsultorio;
    private javax.swing.JComboBox<Object> cmbEspecialidad;
    private javax.swing.JComboBox<String> cmbHora;
    private javax.swing.JComboBox<Object> cmbInstalaciones;
    private javax.swing.JComboBox<Object> cmbProfesional;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JComboBox<Object> cmbTratamiento;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMontoSesion;
    // End of variables declaration//GEN-END:variables
}
